print('construct repository')
print('First modification to test "git diff" command')
print('added by master')
print('added by TestBranch')
print('Push up to remote repository')
print('Edited in remote repository to test "git pull" command')
print('Edited online to test "git fetch" and "git merge" commands')
